#ifndef KIT_PLATFORM_H_
#define KIT_PLATFORM_H_

enum target_platform {
  TARGET_PLATFORM_WIN_32BIT,
  TARGET_PLATFORM_LINUX_32BIT,
  TARGET_PLATFORM_LINUX_64BIT,
  TARGET_PLATFORM_OSX_32BIT,
};

#endif /* KIT_PLATFORM_H_ */

